"""Remove cart_num column from Cart

Revision ID: 3eb23f29c724
Revises: 5b7bcd5d972f
Create Date: 2020-05-28 08:57:19.944124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb23f29c724'
down_revision = '5b7bcd5d972f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nf_calories', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_total_fat', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_saturated_fat', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_cholesterol', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_sodium', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_total_carbohydrate', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_dietary_fiber', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_sugars', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_protein', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('nf_calories', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_total_fat', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_saturated_fat', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_cholesterol', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_sodium', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_total_carbohydrate', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_dietary_fiber', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_sugars', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_protein', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nutrient_multiplier', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('serving_qty', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('serving_unit', sa.String(length=32), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_table('carts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
