"""Add Cart and Food models

Revision ID: 6cf5b3d7956d
Revises: b150ba0467d2
Create Date: 2020-05-21 10:35:58.774314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf5b3d7956d'
down_revision = 'b150ba0467d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_num', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nf_calories', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_total_fat', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_saturated_fat', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_cholesterol', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_sodium', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_total_carbohydrate', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_dietary_fiber', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_sugars', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_protein', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('nf_calories', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_total_fat', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_saturated_fat', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_cholesterol', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_sodium', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_total_carbohydrate', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_dietary_fiber', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_sugars', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('nf_protein', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('serving_qty', sa.Numeric(decimal_return_scale=2), nullable=True),
    sa.Column('serving_unit', sa.String(length=32), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_table('carts')
    # ### end Alembic commands ###
