"""Add timestamp column to Cart model

Revision ID: d5cf336839d4
Revises: e8b916359fb7
Create Date: 2020-06-12 08:47:58.561267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cf336839d4'
down_revision = 'e8b916359fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_carts_timestamp'), 'carts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carts_timestamp'), table_name='carts')
    op.drop_column('carts', 'timestamp')
    # ### end Alembic commands ###
