"""Add img_url column to FoodItem

Revision ID: e8b916359fb7
Revises: 75de31ddec07
Create Date: 2020-06-08 09:39:18.748211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b916359fb7'
down_revision = '75de31ddec07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('img_url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'img_url')
    # ### end Alembic commands ###
